sonar.projectKey=DocFaust_chordpro-converter
sonar.organization=docfaust

sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx,**/test/**

# Abgestimmt mit vitest.config.js coverage.exclude
sonar.coverage.exclusions=**/main.jsx,**/src/convertToChordPro.js
